spring:
  datasource:
    hikari:
      jdbc-url: jdbc:h2:mem:testdb
      username: sa
      passowrd:
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        format_sql: true

buckpal:
  transferThreshold: 10000